#!/bin/bash

script_path=`dirname $BASH_SOURCE`
build_path="$script_path/build_js"

if [ ! -d "$build_path" ]; then
    mkdir "$build_path"
fi

cd "$build_path"
emcmake cmake ..
emmake make
emcc -O2 libquiet_shared.so -o quiet-emscripten.js -s EXPORTED_FUNCTIONS="['_quiet_decoder_recv', '_quiet_decoder_create', '_quiet_decoder_max_len', '_quiet_decoder_flush', '_quiet_decoder_readbuf', '_quiet_decoder_destroy', '_quiet_encoder_emit', '_quiet_encoder_create', '_quiet_encoder_destroy', '_quiet_encoder_set_payload', '_quiet_encoder_profile_str', '_quiet_decoder_profile_str', '_quiet_encoder_opt_set_sample_rate', '_quiet_decoder_opt_set_sample_rate', '_quiet_encoder_clamp_frame_len']" -lliquid -lfec -ljansson
